server:
  port: 8090
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///leyou?characterEncoding=UTF-8
  redis:
    host: 192.168.137.129
  task:
    scheduling:
      pool:
        size: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/xml/**Mapper.xml
  type-aliases-package: com.leyou.order.mapper
ly:
  jwt:
    user:
      cookieName: LY_TOKEN # cookie名称
      cookieDomain: leyou.com # cookie的域
  pay:
    wx:
      appID: wx8397f8696b538317
      mchID: 1473426802
      key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
      notifyUrl: http://sdccuy.natappfree.cc/api/pay/wx/notify
      payType: NATIVE